let Activities = [
    {
        id: 1,
        activity: "Football",
        location: "Hendon",
        price: "20",
        image: "Images/football.png",
        availableSpaces: 5,
    },
    {
    id: 2,
    activity: "Basketball",
    location: "Colindale",
    price: "13",
    image: "Images/basketball.png",
    availableSpaces: 5,
},
{
    id: 3,
    activity: "Tenis",
    location: "Leyton",
    price: "9",
    image: "Images/tenis.png",
    availableSpaces: 5,
},
{
    id: 4,
    activity: "Badminton",
    location: "Walthamstow",
    price: "6",
    image: "Images/badminton.png",
    availableSpaces: 5,
},
{
    id: 5,
    activity: "Cricket",
    location: "Teddington",
    price: "12",
    image: "Images/cricket.png",
    availableSpaces: 5,
},
{
    id: 6,
    activity: "Rugby",
    location: "Euston",
    price: "9",
    image: "Images/rugby.png",
    availableSpaces: 5,
},
{
    id: 7,
    activity: "Volleyball",
    location: "Vauxhall",
    price: "7",
    image: "Images/volleyball.png",
    availableSpaces: 5,
},
{
    id: 8,
    activity: "Table Tenis",
    location: "Tottenham",
    price: "5",
    image: "Images/table-tenis.png",
    availableSpaces: 5,
},
{
    id: 9,
    activity: "Boxing",
    location: "Hackney",
    price: "15",
    image: "Images/boxing.png",
    availableSpaces: 5,
},
{
    id: 10,
    activity: "Swimming",
    location: "Haringay",
    price: "10",
    image: "Images/swimming.png",
    availableSpaces: 5,
}]