let Activities = [
    {
        id: 1,
        activity: "Football",
        location: "London",
        price: "20",
        image: "Images/Football.png",
        availableSpaces: 5,
    },
    {
    id: 2,
    activity: "Basketball",
    location: "London",
    price: "20",
    image: "Images/basketball.png",
    availableSpaces: 5,
},
{
    id: 3,
    activity: "Tenis",
    location: "London",
    price: "20",
    image: "Images/tenis.png",
    availableSpaces: 5,
},
{
    id: 4,
    activity: "Badminton",
    location: "London",
    price: "20",
    image: "Images/badminton.png",
    availableSpaces: 5,
},
{
    id: 5,
    activity: "Cricket",
    location: "London",
    price: "20",
    image: "Images/cricket.png",
    availableSpaces: 5,
},
{
    id: 6,
    activity: "Rugby",
    location: "London",
    price: "20",
    image: "Images/rugby.png",
    availableSpaces: 5,
},
{
    id: 7,
    activity: "Volleyball",
    location: "London",
    price: "20",
    image: "Images/volleyball.png",
    availableSpaces: 5,
},
{
    id: 8,
    activity: "Table Tenis",
    location: "London",
    price: "20",
    image: "Images/table-tenis.png",
    availableSpaces: 5,
},
{
    id: 9,
    activity: "Boxing",
    location: "London",
    price: "20",
    image: "Images/boxing.png",
    availableSpaces: 5,
},
{
    id: 10,
    activity: "Swimming",
    location: "London",
    price: "20",
    image: "Images/swimming.png",
    availableSpaces: 5,
}]